services:
  backend:
    build: ./backend
    ports:
      - "${PORT}:5050" 
    networks:
      - mern_network
    environment:
      MONGO_URI: ${DATABASE_URI}  
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}  

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local
